/* HIMARK · Atlas premium TTS endpoint
   Vercel serverless function (CommonJS).

   POST { text: "..." } → returns audio/mpeg (MP3) generated by
   ElevenLabs. Used in voice mode to give Atlas a natural,
   human-like voice (Jarvis-style) instead of the robotic
   browser-built-in speech synthesizer.

   Env vars:
     - ELEVENLABS_API_KEY    (required)  — your ElevenLabs API key
     - ELEVENLABS_VOICE_ID   (optional)  — voice to use; defaults
                                            to "George" (British
                                            male, warm/sophisticated,
                                            closest to Jarvis-style)

   If ELEVENLABS_API_KEY is unset, returns 503 and the frontend
   falls back to the browser's built-in speech synthesizer.

   Free tier: 10,000 characters/month at no cost. Atlas's voice
   replies are capped at ~110 tokens (~75 words ~ 400 chars),
   so ~25 voice turns per month fit in free tier. Beyond that:
   $5/month for 30k chars (Starter plan).

   Common ElevenLabs voice IDs you can swap in via the env var:
     sLfduly0sixkh8riDzed   Atlas     [HIMARK's chosen voice — current default]
     JBFqnCBsd6RMkjVDRZzb   George    British male, mature, warm
     onwK4e9ZLuTAKqWW03F9   Daniel    British male, deep, calm
     N2lVS1w4EtoT3dr4eOWO   Callum    Scottish male, low, smooth
     CwhRBWXzGAHq8TQ4Fs17   Roger     American male, mature, confident
     IKne3meq5aSn9XLyUdCD   Charlie   Australian male, warm
     bIHbv24MWmeRgasZH58o   Will      American male, soft, friendly
   Find more at https://elevenlabs.io/app/voice-library */

const DEFAULT_VOICE_ID = 'sLfduly0sixkh8riDzed'; // HIMARK's chosen Atlas voice

module.exports = async (req, res) => {
  if (req.method !== 'POST') {
    res.statusCode = 405;
    res.setHeader('Content-Type', 'application/json');
    return res.end(JSON.stringify({ error: 'Method not allowed' }));
  }

  const apiKey = process.env.ELEVENLABS_API_KEY;
  if (!apiKey) {
    /* Premium TTS not configured — frontend will fall back to
       the built-in browser speech synthesizer. */
    res.statusCode = 503;
    res.setHeader('Content-Type', 'application/json');
    return res.end(JSON.stringify({ error: 'TTS not configured', fallback: 'browser' }));
  }

  const voiceId = process.env.ELEVENLABS_VOICE_ID || DEFAULT_VOICE_ID;

  /* Parse body — Vercel may have pre-parsed or sent raw string. */
  let body = req.body;
  if (typeof body === 'string') {
    try { body = JSON.parse(body); } catch (_) { body = {}; }
  }
  if (!body || typeof body !== 'object') body = {};

  const text = String((body && body.text) || '').slice(0, 2000).trim();
  if (!text) {
    res.statusCode = 400;
    res.setHeader('Content-Type', 'application/json');
    return res.end(JSON.stringify({ error: 'text required' }));
  }

  try {
    /* ElevenLabs text-to-speech endpoint.
       eleven_turbo_v2_5 is their fastest model (~300ms first-byte
       latency) and produces quality close to the multilingual_v2
       model. Voice settings tuned for a measured, articulate
       delivery — not too breathy, not too monotone. */
    const upstream = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(voiceId)}`,
      {
        method: 'POST',
        headers: {
          'xi-api-key': apiKey,
          'Content-Type': 'application/json',
          'Accept': 'audio/mpeg'
        },
        body: JSON.stringify({
          text,
          model_id: 'eleven_turbo_v2_5',
          voice_settings: {
            stability: 0.55,        // 0=variable, 1=monotone. 0.5 keeps natural variation
            similarity_boost: 0.78, // how closely it adheres to the voice's reference timbre
            style: 0.18,            // a touch of expressive shaping; too high gets dramatic
            use_speaker_boost: true
          }
        })
      }
    );

    if (!upstream.ok) {
      const errText = await upstream.text().catch(() => '');
      console.error('[atlas tts] elevenlabs error', upstream.status, errText.slice(0, 400));
      res.statusCode = upstream.status === 401 ? 401 : 502;
      res.setHeader('Content-Type', 'application/json');
      return res.end(JSON.stringify({
        error: 'TTS upstream failed',
        upstreamStatus: upstream.status
      }));
    }

    /* Pipe the audio bytes back to the browser. Vercel functions
       buffer the body, but at ~75 words per reply this is ~30-50KB
       per response — well within the 4.5MB function response cap. */
    const arr = await upstream.arrayBuffer();
    res.statusCode = 200;
    res.setHeader('Content-Type', 'audio/mpeg');
    res.setHeader('Cache-Control', 'no-store');
    res.setHeader('Content-Length', arr.byteLength);
    return res.end(Buffer.from(arr));
  } catch (err) {
    console.error('[atlas tts] handler error', err && err.message);
    res.statusCode = 500;
    res.setHeader('Content-Type', 'application/json');
    return res.end(JSON.stringify({ error: 'TTS failed' }));
  }
};
